name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.6

    - name: Change directory to Task8/testing_task_manager
      run: cd Task8/testing_task_manager

    - name: Install dependencies
      working-directory: Task8/testing_task_manager
      run: go mod tidy

    - name: Run controller tests
      working-directory: Task8/testing_task_manager
      run: go test ./Delivery/controllers -v

    - name: Run infrastructure tests
      working-directory: Task8/testing_task_manager
      run: go test ./Infrastructure -v

    - name: Run usecase tests
      working-directory: Task8/testing_task_manager
      run: go test ./Usecases -v

    - name: Build application
      working-directory: Task8/testing_task_manager
      run: go build -v ./...
