// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "test_task_manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// TaskUseCase is an autogenerated mock type for the TaskUseCase type
type TaskUseCase struct {
	mock.Mock
}

type TaskUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskUseCase) EXPECT() *TaskUseCase_Expecter {
	return &TaskUseCase_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function with given fields: c, newTask
func (_m *TaskUseCase) CreateTask(c interface{}, newTask domain.Task) (*domain.Task, error) {
	ret := _m.Called(c, newTask)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, domain.Task) (*domain.Task, error)); ok {
		return rf(c, newTask)
	}
	if rf, ok := ret.Get(0).(func(interface{}, domain.Task) *domain.Task); ok {
		r0 = rf(c, newTask)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, domain.Task) error); ok {
		r1 = rf(c, newTask)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUseCase_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type TaskUseCase_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - c context.Context
//   - newTask domain.Task
func (_e *TaskUseCase_Expecter) CreateTask(c interface{}, newTask interface{}) *TaskUseCase_CreateTask_Call {
	return &TaskUseCase_CreateTask_Call{Call: _e.mock.On("CreateTask", c, newTask)}
}

func (_c *TaskUseCase_CreateTask_Call) Run(run func(c context.Context, newTask domain.Task)) *TaskUseCase_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Task))
	})
	return _c
}

func (_c *TaskUseCase_CreateTask_Call) Return(_a0 *domain.Task, _a1 error) *TaskUseCase_CreateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUseCase_CreateTask_Call) RunAndReturn(run func(context.Context, domain.Task) (*domain.Task, error)) *TaskUseCase_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function with given fields: c, taskID
func (_m *TaskUseCase) DeleteTask(c context.Context, taskID string) error {
	ret := _m.Called(c, taskID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskUseCase_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type TaskUseCase_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - c context.Context
//   - taskID string
func (_e *TaskUseCase_Expecter) DeleteTask(c interface{}, taskID interface{}) *TaskUseCase_DeleteTask_Call {
	return &TaskUseCase_DeleteTask_Call{Call: _e.mock.On("DeleteTask", c, taskID)}
}

func (_c *TaskUseCase_DeleteTask_Call) Run(run func(c context.Context, taskID string)) *TaskUseCase_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TaskUseCase_DeleteTask_Call) Return(_a0 error) *TaskUseCase_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskUseCase_DeleteTask_Call) RunAndReturn(run func(context.Context, string) error) *TaskUseCase_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskByID provides a mock function with given fields: c, taskID
func (_m *TaskUseCase) GetTaskByID(c context.Context, taskID string) (*domain.Task, error) {
	ret := _m.Called(c, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Task, error)); ok {
		return rf(c, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Task); ok {
		r0 = rf(c, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUseCase_GetTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskByID'
type TaskUseCase_GetTaskByID_Call struct {
	*mock.Call
}

// GetTaskByID is a helper method to define mock.On call
//   - c context.Context
//   - taskID string
func (_e *TaskUseCase_Expecter) GetTaskByID(c interface{}, taskID interface{}) *TaskUseCase_GetTaskByID_Call {
	return &TaskUseCase_GetTaskByID_Call{Call: _e.mock.On("GetTaskByID", c, taskID)}
}

func (_c *TaskUseCase_GetTaskByID_Call) Run(run func(c context.Context, taskID string)) *TaskUseCase_GetTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TaskUseCase_GetTaskByID_Call) Return(_a0 *domain.Task, _a1 error) *TaskUseCase_GetTaskByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUseCase_GetTaskByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Task, error)) *TaskUseCase_GetTaskByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasks provides a mock function with given fields: c
func (_m *TaskUseCase) GetTasks(c context.Context) ([]domain.Task, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Task, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Task); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUseCase_GetTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasks'
type TaskUseCase_GetTasks_Call struct {
	*mock.Call
}

// GetTasks is a helper method to define mock.On call
//   - c context.Context
func (_e *TaskUseCase_Expecter) GetTasks(c interface{}) *TaskUseCase_GetTasks_Call {
	return &TaskUseCase_GetTasks_Call{Call: _e.mock.On("GetTasks", c)}
}

func (_c *TaskUseCase_GetTasks_Call) Run(run func(c context.Context)) *TaskUseCase_GetTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TaskUseCase_GetTasks_Call) Return(_a0 []domain.Task, _a1 error) *TaskUseCase_GetTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUseCase_GetTasks_Call) RunAndReturn(run func(context.Context) ([]domain.Task, error)) *TaskUseCase_GetTasks_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function with given fields: c, taskID, updatedTask
func (_m *TaskUseCase) UpdateTask(c interface{}, taskID string, updatedTask domain.Task) (*domain.Task, error) {
	ret := _m.Called(c, taskID, updatedTask)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, string, domain.Task) (*domain.Task, error)); ok {
		return rf(c, taskID, updatedTask)
	}
	if rf, ok := ret.Get(0).(func(interface{}, string, domain.Task) *domain.Task); ok {
		r0 = rf(c, taskID, updatedTask)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, string, domain.Task) error); ok {
		r1 = rf(c, taskID, updatedTask)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskUseCase_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type TaskUseCase_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - c context.Context
//   - taskID string
//   - updatedTask domain.Task
func (_e *TaskUseCase_Expecter) UpdateTask(c interface{}, taskID interface{}, updatedTask interface{}) *TaskUseCase_UpdateTask_Call {
	return &TaskUseCase_UpdateTask_Call{Call: _e.mock.On("UpdateTask", c, taskID, updatedTask)}
}

func (_c *TaskUseCase_UpdateTask_Call) Run(run func(c context.Context, taskID string, updatedTask domain.Task)) *TaskUseCase_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.Task))
	})
	return _c
}

func (_c *TaskUseCase_UpdateTask_Call) Return(_a0 *domain.Task, _a1 error) *TaskUseCase_UpdateTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskUseCase_UpdateTask_Call) RunAndReturn(run func(context.Context, string, domain.Task) (*domain.Task, error)) *TaskUseCase_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskUseCase creates a new instance of TaskUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUseCase {
	mock := &TaskUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
