// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "test_task_manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// UserUseCase is an autogenerated mock type for the UserUseCase type
type UserUseCase struct {
	mock.Mock
}

type UserUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UserUseCase) EXPECT() *UserUseCase_Expecter {
	return &UserUseCase_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: c, user
func (_m *UserUseCase) CreateUser(c context.Context, user domain.User) error {
	ret := _m.Called(c, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = rf(c, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserUseCase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserUseCase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - c context.Context
//   - user domain.User
func (_e *UserUseCase_Expecter) CreateUser(c interface{}, user interface{}) *UserUseCase_CreateUser_Call {
	return &UserUseCase_CreateUser_Call{Call: _e.mock.On("CreateUser", c, user)}
}

func (_c *UserUseCase_CreateUser_Call) Run(run func(c context.Context, user domain.User)) *UserUseCase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *UserUseCase_CreateUser_Call) Return(_a0 error) *UserUseCase_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserUseCase_CreateUser_Call) RunAndReturn(run func(context.Context, domain.User) error) *UserUseCase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: c
func (_m *UserUseCase) GetUsers(c context.Context) ([]domain.User, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.User, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.User); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type UserUseCase_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - c context.Context
func (_e *UserUseCase_Expecter) GetUsers(c interface{}) *UserUseCase_GetUsers_Call {
	return &UserUseCase_GetUsers_Call{Call: _e.mock.On("GetUsers", c)}
}

func (_c *UserUseCase_GetUsers_Call) Run(run func(c context.Context)) *UserUseCase_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserUseCase_GetUsers_Call) Return(_a0 []domain.User, _a1 error) *UserUseCase_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_GetUsers_Call) RunAndReturn(run func(context.Context) ([]domain.User, error)) *UserUseCase_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: c, user
func (_m *UserUseCase) Login(c context.Context, user domain.User) (string, error) {
	ret := _m.Called(c, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) (string, error)); ok {
		return rf(c, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.User) string); ok {
		r0 = rf(c, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = rf(c, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UserUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - c context.Context
//   - user domain.User
func (_e *UserUseCase_Expecter) Login(c interface{}, user interface{}) *UserUseCase_Login_Call {
	return &UserUseCase_Login_Call{Call: _e.mock.On("Login", c, user)}
}

func (_c *UserUseCase_Login_Call) Run(run func(c context.Context, user domain.User)) *UserUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.User))
	})
	return _c
}

func (_c *UserUseCase_Login_Call) Return(_a0 string, _a1 error) *UserUseCase_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_Login_Call) RunAndReturn(run func(context.Context, domain.User) (string, error)) *UserUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// PromoteUser provides a mock function with given fields: c, username
func (_m *UserUseCase) PromoteUser(c context.Context, username string) (*domain.User, error) {
	ret := _m.Called(c, username)

	if len(ret) == 0 {
		panic("no return value specified for PromoteUser")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(c, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(c, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUseCase_PromoteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoteUser'
type UserUseCase_PromoteUser_Call struct {
	*mock.Call
}

// PromoteUser is a helper method to define mock.On call
//   - c context.Context
//   - username string
func (_e *UserUseCase_Expecter) PromoteUser(c interface{}, username interface{}) *UserUseCase_PromoteUser_Call {
	return &UserUseCase_PromoteUser_Call{Call: _e.mock.On("PromoteUser", c, username)}
}

func (_c *UserUseCase_PromoteUser_Call) Run(run func(c context.Context, username string)) *UserUseCase_PromoteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserUseCase_PromoteUser_Call) Return(_a0 *domain.User, _a1 error) *UserUseCase_PromoteUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserUseCase_PromoteUser_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *UserUseCase_PromoteUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserUseCase creates a new instance of UserUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUseCase {
	mock := &UserUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
